on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v2
    - name: Send notifications
      env:
        LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
        REGION: ${{ secrets.REGION }}
      run: |
        bash water-cut-notify.sh